### ISSUE TITLE
Compilation failure: USA.IDX and USA.MSG

### ISSUE THREAD

**Issue by ParzivalWolfram** [AR1972/astro#1]
On using BUILDALL, eventually, build fails due to USA.IDX and USA.MSG not having matching COMMON headers, though they do appear to share exactly the same COMMON declaration. Compiling on MS-DOS 6.22 in 86box, using either a Pentium Overdrive or 486DX.

**Comment by creeperpower** [comment]
You can also go to the c:\astro\messages directory and then run `buildidx usa.msg`
